import { supabase } from './supabase.js';
const app=document.querySelector('#admin-app');
const PDFJS=window.pdfjsLib;
if(PDFJS) PDFJS.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.js';
const competitions=['Premier League','La Liga','Serie A','Bundesliga','Ligue 1','Champions League','Europa League','CAF'];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const money=v=>`₦${Number(v||0).toLocaleString('en-NG',{maximumFractionDigits:2})}`;
async function session(){return (await supabase.auth.getSession()).data.session;}
function loginView(message=''){
 app.innerHTML=`<div class="wrap"><section class="card login-card"><h1>StatKick Admin</h1><p class="muted">Private administration portal</p><form id="login-form" class="form"><label>Email<input id="login-email" class="input" type="email" required></label><label>Password<input id="login-password" class="input" type="password" required></label><button>Sign in</button></form><div class="message">${esc(message)}</div></section></div>`;
 document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const m=document.querySelector('.message');m.textContent='Signing in…';const {error}=await supabase.auth.signInWithPassword({email:document.querySelector('#login-email').value.trim(),password:document.querySelector('#login-password').value});if(error)m.textContent=error.message;else load();};
}
const monthMap={jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11};
function dateFrom(s){let m=s.match(/\b(20\d{2})[-\/](\d{1,2})[-\/](\d{1,2})\b/);if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));m=s.match(/\b(\d{1,2})[-\/](\d{1,2})[-\/](20\d{2})\b/);if(m)return new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));m=s.match(/\b(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(20\d{2})\b/i);if(m)return new Date(Date.UTC(+m[3],monthMap[m[2].slice(0,3).toLowerCase()],+m[1]));return null;}
function parseLine(line){
 const clean=line.replace(/[|•·]+/g,' ').replace(/\s+/g,' ').trim();if(!clean)return null;const comp=competitions.find(c=>clean.toLowerCase().includes(c.toLowerCase()));const d=dateFrom(clean);if(!d)return null;const tm=clean.match(/\b([01]?\d|2[0-3])[:.]([0-5]\d)\b/);if(tm)d.setUTCHours(+tm[1],+tm[2],0,0);
 const vs=clean.match(/(.+?)\s+(?:vs\.?|v\.?|versus)\s+(.+?)(?=\s+(?:\d{1,2}[:.]\d{2}|\d{1,2}[-\/]\d{1,2}[-\/]20\d{2}|\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))|$)/i);if(!vs)return null;
 let home=vs[1].replace(comp||'','').replace(/\b(20\d{2})[-\/]\d{1,2}[-\/]\d{1,2}\b|\b\d{1,2}[-\/]\d{1,2}[-\/]20\d{2}\b/gi,'').replace(/[-–,:]+$/,'').trim();
 let away=vs[2].replace(/\b(20\d{2})[-\/]\d{1,2}[-\/]\d{1,2}\b|\b\d{1,2}[-\/]\d{1,2}[-\/]20\d{2}\b/gi,'').replace(/^[-–,:]+/,'').trim();
 if(!home||!away||home.length>100||away.length>100)return null;return {competition:comp||'Premier League',home_team:home,away_team:away,kickoff_at:d.toISOString()};
}
async function readPdf(file){if(!PDFJS)throw new Error('PDF reader unavailable. Refresh the Admin page.');const pdf=await PDFJS.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const tc=await page.getTextContent();text+=tc.items.map(x=>x.str).join(' ')+'\n';}const seen=new Set(),matches=[];for(const line of text.split(/\n+/)){const m=parseLine(line);if(!m)continue;const k=[m.competition,m.home_team,m.away_team,m.kickoff_at].join('|').toLowerCase();if(!seen.has(k)){seen.add(k);matches.push(m);}}return matches;}
async function load(){
 const s=await session();if(!s){loginView();return;}let {data:admin}=await supabase.from('admin_users').select('active,is_owner').eq('user_id',s.user.id).maybeSingle();if(!admin){const {data:b,error}=await supabase.rpc('bootstrap_statkick_owner');if(!error&&b)admin={active:true,is_owner:true};}if(!admin?.active){app.innerHTML='<div class="wrap"><section class="card"><h1>Admin access denied</h1><p class="muted">This account is not an active StatKick administrator.</p></section></div>';return;}
 const [{count:users},{count:pools},{count:entries},{data:pay},{data:poolRows},{data:admins}]=await Promise.all([supabase.from('profiles').select('*',{count:'exact',head:true}),supabase.from('pools').select('*',{count:'exact',head:true}),supabase.from('pool_entries').select('*',{count:'exact',head:true}),supabase.from('payout_settings').select('bank_name,account_name,account_number').eq('id',true).maybeSingle(),supabase.from('pools').select('id,entry_fee,status,max_entries,locked_at,created_at,fixtures(home_team,away_team,kickoff_at,competitions(name))').order('created_at',{ascending:false}).limit(50),supabase.rpc('list_statkick_admins')]);
 const ids=(poolRows||[]).map(p=>p.id);let lc={};if(ids.length){const {data:lines}=await supabase.from('pool_market_lines').select('pool_id,locked_at').in('pool_id',ids);(lines||[]).forEach(x=>{lc[x.pool_id]??={count:0,locked:0};lc[x.pool_id].count++;if(x.locked_at)lc[x.pool_id].locked++;});}
 const poolHtml=(poolRows||[]).map(p=>{const f=p.fixtures||{},x=lc[p.id]||{count:0,locked:0},can=p.status==='open'&&!p.locked_at;return `<div class="pool-row"><div><b>${esc(f.home_team||'Home')} vs ${esc(f.away_team||'Away')}</b><div class="muted">${esc(f.competitions?.name||'Football')} · ${f.kickoff_at?new Date(f.kickoff_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'}):'No kickoff'}</div></div><div>${money(p.entry_fee)} · ${esc(p.status)}<div class="muted">Lines: ${x.count}/20 ${x.locked===20?'· LOCKED':''}</div></div><div>${can?`<button class="lock-pool" data-pool="${p.id}">Generate & Lock Lines</button>`:`<span class="muted">${p.locked_at?'Lines locked':'Not lockable'}</span>`}</div></div>`;}).join('')||'<p class="muted">No pools created yet.</p>';
 const adminRows=(admins||[]).map(a=>`<div class="pool-row"><div><b>${esc(a.email||a.user_id)}</b><div class="muted">${a.is_owner?'Owner':'Administrator'} · ${a.active?'Active':'Inactive'}</div></div><div>${a.is_owner?'Protected owner account':'Administrative access'}</div><div>${a.is_owner?'':'<button class="remove-admin" data-id="'+esc(a.user_id)+'">Remove access</button>'}</div></div>`).join('')||'<p class="muted">No administrators configured.</p>';
 app.innerHTML=`<div class="wrap"><div class="top"><div><h1>StatKick Admin</h1><p class="muted">Private operations dashboard · Owner protected</p></div><button id="out">Sign out</button></div><div class="grid"><div class="card">Players<div class="value">${users||0}</div></div><div class="card">Pools<div class="value">${pools||0}</div></div><div class="card">Entries<div class="value">${entries||0}</div></div><div class="card">Status<div class="value">Ready</div></div></div>
 <section class="card section"><h2>Three-day match PDF upload</h2><p class="muted">Upload one PDF containing up to three days of upcoming matches. Review the detected matches before importing. After the three days finish, upload the next PDF. Existing fixtures are skipped automatically.</p><p class="muted">Supported row style: <b>Premier League | Arsenal vs Chelsea | 12 Sep 2026 | 15:00</b></p><form id="pdf-form" class="form"><label>Three-day match PDF<input id="pdf-file" class="input" type="file" accept="application/pdf,.pdf" required></label><button>Read PDF</button></form><div id="pdf-msg" class="message"></div><div id="pdf-preview" class="pool-list"></div></section>
 <section class="card section"><h2>Single match upload</h2><form id="single-form" class="form"><label>Competition<select id="sc" class="input">${competitions.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Home team<input id="sh" class="input" required></label><label>Away team<input id="sa" class="input" required></label><label>Kickoff<input id="sk" class="input" type="datetime-local" required></label><button>Upload single match</button></form><div id="single-msg" class="message"></div></section>
 <section class="card section"><h2>Administrators</h2><p class="muted">Only the owner can add or remove administrators. The owner account is protected.</p><form id="admin-form" class="form"><label>Add registered user by email<input id="admin-email" class="input" type="email" required></label><button>Add administrator</button></form><div id="admin-msg" class="message"></div><div class="pool-list">${adminRows}</div></section>
 <section class="card section"><h2>Pool & market controls</h2><div class="pool-list">${poolHtml}</div><div id="pool-msg" class="message"></div></section>
 <section class="card section"><h2>Player payment account</h2><form id="pay-form" class="form"><label>Bank name<input id="bank" class="input" required value="${esc(pay?.bank_name||'')}"></label><label>Account name<input id="account-name" class="input" required value="${esc(pay?.account_name||'')}"></label><label>Account number<input id="account-number" class="input" inputmode="numeric" pattern="[0-9]{10}" maxlength="10" required value="${esc(pay?.account_number||'')}"></label><button>Save payment account</button></form><div id="pay-msg" class="message"></div></section></div>`;
 document.querySelector('#out').onclick=()=>supabase.auth.signOut();
 document.querySelector('#pdf-form').onsubmit=async e=>{e.preventDefault();const file=document.querySelector('#pdf-file').files[0],msg=document.querySelector('#pdf-msg'),preview=document.querySelector('#pdf-preview');if(!file)return;if(file.size>20*1024*1024){msg.textContent='PDF is too large. Maximum 20 MB.';return;}msg.textContent='Reading PDF…';preview.innerHTML='';try{const matches=await readPdf(file);const days=[...new Set(matches.map(m=>m.kickoff_at.slice(0,10)))].sort();if(!matches.length){msg.textContent='No match rows detected. Use the supported row style shown above.';return;}if(days.length>3){msg.textContent='This PDF contains more than 3 different match dates. Please upload only three days.';return;}preview.innerHTML=`<div class="message">Detected ${matches.length} matches across ${days.length} day(s).</div>${matches.map((m,i)=>`<div class="pool-row"><div><b>${i+1}. ${esc(m.home_team)} vs ${esc(m.away_team)}</b><div class="muted">${esc(m.competition)} · ${new Date(m.kickoff_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</div></div></div>`).join('')}<button id="import-pdf" type="button">Import detected matches</button>`;document.querySelector('#import-pdf').onclick=async()=>{const b=document.querySelector('#import-pdf');b.disabled=true;b.textContent='Importing…';msg.textContent='Creating fixtures and pools…';const {data,error}=await supabase.rpc('admin_import_fixture_batch',{p_matches:matches});if(error){msg.textContent=`Import failed: ${error.message}`;b.disabled=false;b.textContent='Import detected matches';return;}msg.textContent=`Import complete: ${data?.created||0} created, ${data?.skipped||0} already existed, ${data?.invalid||0} rejected.`;preview.innerHTML='';document.querySelector('#pdf-form').reset();await load();};}catch(err){msg.textContent=`Could not read PDF: ${err.message}`;}};
 document.querySelector('#single-form').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#single-msg'),d=new Date(document.querySelector('#sk').value);if(d<=new Date()){msg.textContent='Kickoff must be in the future.';return;}const {error}=await supabase.rpc('admin_create_fixture_and_pool',{p_competition:document.querySelector('#sc').value,p_home_team:document.querySelector('#sh').value.trim(),p_away_team:document.querySelector('#sa').value.trim(),p_kickoff_at:d.toISOString(),p_external_id:null});msg.textContent=error?`Upload failed: ${error.message}`:'Match uploaded successfully.';if(!error){e.target.reset();await load();}};
 if(admin.is_owner){document.querySelector('#admin-form').onsubmit=async e=>{e.preventDefault();const m=document.querySelector('#admin-msg');const {error}=await supabase.rpc('add_statkick_admin_by_email',{p_email:document.querySelector('#admin-email').value.trim()});m.textContent=error?error.message:'Administrator added successfully.';if(!error)load();};document.querySelectorAll('.remove-admin').forEach(b=>b.onclick=async()=>{if(!confirm('Remove administrator access?'))return;const {error}=await supabase.rpc('remove_statkick_admin',{p_user_id:b.dataset.id});if(error)alert(error.message);else load();});}else document.querySelector('#admin-form').style.display='none';
 document.querySelectorAll('.lock-pool').forEach(b=>b.onclick=async()=>{b.disabled=true;const {data,error}=await supabase.rpc('lock_pool',{p_pool_id:b.dataset.pool});const m=document.querySelector('#pool-msg');if(error){m.textContent=error.message;b.disabled=false;}else{m.textContent=`Pool locked. ${data?.lines||20} market lines fixed.`;load();}});
 document.querySelector('#pay-form').onsubmit=async e=>{e.preventDefault();const n=document.querySelector('#account-number').value.trim(),m=document.querySelector('#pay-msg');if(!/^\d{10}$/.test(n)){m.textContent='Enter a valid 10-digit Nigerian account number.';return;}const {error}=await supabase.from('payout_settings').upsert({id:true,bank_name:document.querySelector('#bank').value.trim(),account_name:document.querySelector('#account-name').value.trim(),account_number:n,updated_at:new Date().toISOString()},{onConflict:'id'});m.textContent=error?error.message:'Payment account saved.';};
}
supabase.auth.onAuthStateChange(()=>load());load();
