import { supabase } from './supabase.js';

const markets=[['total_goals','Total Goals','OVER 2.5','UNDER 2.5'],['total_corners','Total Corners','OVER 9.5','UNDER 9.5'],['total_cards','Total Cards','OVER 3.5','UNDER 3.5'],['total_fouls','Total Fouls','OVER 22.5','UNDER 22.5'],['shots_on_target','Shots on Target','OVER 7.5','UNDER 7.5'],['total_offsides','Total Offsides','OVER 2.5','UNDER 2.5'],['total_passes','Total Passes','OVER 850.5','UNDER 850.5'],['home_possession','Home Possession','OVER 50.5','UNDER 50.5'],['away_possession','Away Possession','OVER 49.5','UNDER 49.5'],['home_shots','Home Shots','OVER 11.5','UNDER 11.5'],['away_shots','Away Shots','OVER 9.5','UNDER 9.5'],['home_corners','Home Corners','OVER 4.5','UNDER 4.5'],['away_corners','Away Corners','OVER 3.5','UNDER 3.5'],['home_cards','Home Cards','OVER 1.5','UNDER 1.5'],['away_cards','Away Cards','OVER 1.5','UNDER 1.5'],['home_shots_on_target','Home Shots on Target','OVER 3.5','UNDER 3.5'],['away_shots_on_target','Away Shots on Target','OVER 2.5','UNDER 2.5'],['both_teams_to_score','Both Teams to Score','YES','NO'],['red_card','Red Card','YES','NO'],['first_half_goals','First-Half Goals','OVER 1.5','UNDER 1.5']];
let pools=[];let selected=new Map();const app=document.querySelector('#app');

async function loadPools(){
  const {data,error}=await supabase.from('pools').select('id,entry_fee,status,fixture:fixtures(id,home_team,away_team,kickoff_at,competition:competitions(name))').eq('status','open').order('created_at',{ascending:false});
  if(error) throw error;
  pools=(data||[]).map(p=>({id:p.id,league:p.fixture?.competition?.name||'Football',home:p.fixture?.home_team||'Home',away:p.fixture?.away_team||'Away',kick:p.fixture?.kickoff_at?new Date(p.fixture.kickoff_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—',date:p.fixture?.kickoff_at?new Date(p.fixture.kickoff_at).toLocaleDateString([], {weekday:'short',day:'2-digit',month:'short'}):'—',players:0,prize:'—',entry:p.entry_fee||2000}));
}
function shell(content,page='home'){app.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><span class="brand-mark">S</span>StatKick</div><nav class="nav">${[['home','Pools'],['leaderboard','Leaderboard'],['wallet','Wallet']].map(([p,n])=>`<button class="${page===p?'active':''}" data-page="${p}">${n}</button>`).join('')}</nav><div class="userbox"><span class="wallet">Wallet</span><span class="avatar">EP</span></div></header><main>${content}</main><button class="chat" onclick="alert('StatKick Support AI will be connected through the secure backend.')">?</button></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));}
function home(){shell(`<section class="hero"><div><div class="eyebrow">Football statistics pools</div><h1>Predict smarter.<br><span class="gold-text">Compete for the pool.</span></h1><p>Choose exactly 10 statistics from 20 markets. Every correct prediction earns one point. StatKick settles only after official statistics are confirmed.</p></div><button class="btn gold" onclick="document.querySelector('.pools').scrollIntoView({behavior:'smooth'})">Explore pools</button></section><div class="notice">Connected to the new StatKick Supabase backend. Entry and wallet transactions will be processed server-side.</div><div class="section-head"><h2>Open pools</h2><span class="muted">Live database</span></div><div class="pools">${pools.length?pools.map((p,i)=>`<article class="pool card"><div class="league"><span class="badge">${p.league}</span><span class="muted">${p.date} · ${p.kick}</span></div><div class="teams"><div class="team">${p.home}</div><div class="vs">VS</div><div class="team">${p.away}</div></div><div class="pool-meta"><div><small>Players</small><b>—</b></div><div><small>Prize pool</small><b>Pending</b></div><div><small>Entry</small><b>₦${Number(p.entry).toLocaleString()}</b></div></div><div class="pool-foot"><span class="muted">Locks before kickoff</span><button class="btn gold" onclick="openPool(${i})">Predict</button></div></article>`).join(''):`<div class="card" style="padding:28px"><h3>No open pools yet</h3><p class="muted">Pools will appear here when an administrator publishes fixtures and opens entries.</p></div>`}</div>`);}
function openPool(i){selected.clear();const p=pools[i];shell(`<div class="section-head"><div><div class="eyebrow">${p.league}</div><h2>${p.home} vs ${p.away}</h2><span class="muted">${p.date} · ${p.kick}</span></div><button class="btn dark" onclick="home()">Back</button></div><div class="card" style="padding:20px"><div style="display:flex;justify-content:space-between"><b>Select exactly 10 markets</b><span id="count" class="gold-text"><b>0 / 10</b></span></div><div class="progress"><span id="bar"></span></div><div class="selector">${markets.map((m,j)=>`<article class="market" id="m${j}"><div><div class="market-name">${m[1]}</div><div class="market-line">${m[2]} / ${m[3]}</div></div><div class="choices"><button class="choice" id="a${j}" onclick="pick(${j},0)">${m[2]}</button><button class="choice" id="b${j}" onclick="pick(${j},1)">${m[3]}</button></div></article>`).join('')}</div></div><div class="sticky-entry"><div><small class="muted">Entry total</small><div><b>₦${Number(p.entry).toLocaleString()}</b> · <span id="summary">Select 10 markets</span></div></div><button id="submit" class="btn gold" disabled onclick="submitEntry()">Continue</button></div>`,'pool');}
window.pick=(j,s)=>{if(!selected.has(j)&&selected.size>=10)return;if(selected.has(j)&&selected.get(j)===s)selected.delete(j);else selected.set(j,s);const card=document.getElementById('m'+j);card.classList.toggle('selected',selected.has(j));card.querySelectorAll('.choice').forEach(x=>x.classList.remove('chosen'));if(selected.has(j))document.getElementById((s?'b':'a')+j).classList.add('chosen');document.getElementById('count').innerHTML=`<b>${selected.size} / 10</b>`;document.getElementById('bar').style.width=`${selected.size*10}%`;document.getElementById('summary').textContent=selected.size===10?'Ready to enter':`Select ${10-selected.size} more`;document.getElementById('submit').disabled=selected.size!==10;};
window.submitEntry=async()=>{if(selected.size!==10)return;alert('Your 10 selections passed client-side validation. Secure server-side entry charging and authenticated submission are the next backend step.');console.log([...selected].map(([j,s])=>({market:markets[j][0],side:markets[j][s+2]})));};
function leaderboard(){shell(`<div class="hero"><div><div class="eyebrow">Competition</div><h1>Leaderboard</h1><p>Scores will be populated from settled official statistics.</p></div></div><div class="card" style="padding:28px"><p class="muted">No settled pool results are available yet.</p></div>`,'leaderboard');}
function wallet(){shell(`<div class="section-head"><div><div class="eyebrow">Your account</div><h2>Wallet</h2></div><button class="btn gold" onclick="alert('Secure deposit flow will be connected next.')">Deposit</button></div><div class="wallet-card card"><div><small class="muted">Available balance</small><div class="balance">₦0.00</div></div><button class="btn dark" onclick="alert('Secure withdrawal flow will be connected next.')">Withdraw</button></div><div class="section-head"><h2>Transactions</h2></div><div class="transactions card" style="padding:20px"><p class="muted">Sign in to view your wallet ledger.</p></div>`,'wallet');}
function navigate(p){if(p==='leaderboard')leaderboard();else if(p==='wallet')wallet();else home();}
loadPools().then(home).catch(err=>{console.error(err);shell(`<div class="card" style="padding:28px"><h2>StatKick is starting</h2><p class="muted">The new database is connected, but the public pool feed is not populated yet.</p></div>`);});
